// Fun Fact: I drink a looot of water.
// Twitter: @anne_melody

print(" ❄                ❄            ❄ ")
print("      ❄     ❄                    ")
print("                      ❄          ")
print("❄         ❄                 ❄    ")
print("     ❄           ❄     ❄         ")
print("             HHHH        ❄       ")
print(" ❄          HHHHHH               ")
print("     ❄    HHHHHHHHHH    ❄     ❄  ")
print("         ❄  ⚫ ⚫   ❄            ")
print("        ❄     🥕     ❄           ")
print("  ❄       ❄   ✔️   ❄         ❄   ")
print("      🔶🔶🔶 ❄ ❄ 🔶             ")
print("         ❄ 🔸🔸🔸🔸 ❄           ")
print("       ❄      ⚫️  🔸  ❄          ")
print("      ❄       ⚫️   🔸  ❄         ")
print("      ❄       ⚫️       ❄         ")
print("       ❄              ❄          ")
print("          ❄   ❄   ❄              ")
